# Netlify CMS configuration for use with ClearStatus
backend:
  name: git-gateway
  branch: master

# This line should *not* be indented
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

## Content definition
collections:
  - name: "issue"
    label: "Events"
    folder: "content/default/issues"
    create: true
    slug: "{{ .Site.Params.NetlifySlug }}"
    fields:
      - {label: "Section", name: "section", widget: "hidden", default: "issue"}
      - {label: "Title", name: "title", widget: "string", hint: "A short descriptive title for the event."}
      - {label: "Date", name: "date", widget: "datetime", hint: "The date and time at which the event started or is scheduled."}
      - label: "Status"
        name: "status"
        hint: "The current state of the affected systems."
        widget: "select"
        default: "in_progress"
        options:
          - { label: "Resolved", value: "resolved" }
          - { label: "In progress", value: "in_progress" }
          - { label: "Scheduled", value: "scheduled" }
      - label: "Current severity"
        name: "current_severity"
        hint: "How severe is the event for the affected systme right now."
        widget: "select"
        default: "down"
        options:
          - { label: "Up", value: "ok" }
          - { label: "Disrupted", value: "disrupted" }
          - { label: "Down", value: "down" }
          - { label: "Monitoring", value: "monitoring" }
          - { label: "Maintenance", value: "maintenance" }
      - label: "Max severity"
        name: "max_severity"
        hint: "What was the maximum severity of the event until its resolution. Used when the event is displayed in the Past events section."
        widget: "select"
        default: "down"
        options:
          - { label: "Up", value: "ok" }
          - { label: "Disrupted", value: "disrupted" }
          - { label: "Down", value: "down" }
          - { label: "Monitoring", value: "monitoring" }
          - { label: "Maintenance", value: "maintenance" }
      - label: "Resolved on"
        name: "resolved_on"
        widget: "datetime"
        hint: ""
      - label: "Affected systems"
        name: "affected"
        hint: "Which of your systems are affected by the event. Use exact same name as in your config file."
        widget: "select"
        multiple: true
        options:
{{ range .Site.Params.Systems }}          - { label: "{{ .name }}", value: "{{ .name }}" }
{{ end }}
      - label: "Event description"
        name: "body"
        hint: "Description of the event as it happens and what you do about it. You can come back several times and update that description."
        widget: "markdown"
        default: ""


  - name: "settings"
    label: "Settings"
    description: "General configuration for your status page. Saving these settings will overwrite those in your git repository."
    delete: false
    editor:
      preview: false
    files:
      - name: "general"
        label: "Status page configuration"
        file: "config.yml"
          - label: 'Site title'
            hint: 'Complete page title'
            name: 'title'
            widget: 'string'
          - label: 'Language code'
            hint: 'Language code for the status page'
            name: 'languageCode'
            widget: 'string'
            default: "en"


          # Hidden settings, not to be modified or not in the UI
          - label: 'Build future events'
            name: 'buildFuture'
            widget: 'boolean'
            default: true
          - label: 'theme'
            name: 'theme'
            widget: 'hidden'
            default: 'clearstatus'
          - label: 'assetsDir'
            name: 'assetsDir'
            widget: 'hidden'
            default: 'themes/clearstatustheme/assets'
          - label: 'contentDir'
            name: 'contentDir'
            widget: 'hidden'
            default: 'content/default'



          - label: 'preserveTaxonomyNames'
            name: 'preserveTaxonomyNames'
            widget: 'hidden'
            default: 'true'
          - label: "taxonomies"
            name: taxonomies
            widget: "hidden"
            fields:
          - {label: "affected", name: "affected", widget: "hidden", default: "affected"}